@echo off
echo [TEST] Simulating Aegis-Guard Threat...
echo [INFO] Copying notepad to temp as a fake malicious tool...
copy C:\Windows\System32\notepad.exe %TEMP%\mimikatz.exe > nul
echo [INFO] Launching fake tool from suspicious path...
start "" %TEMP%\mimikatz.exe
echo [INFO] Waiting for agent to detect...
timeout /t 5 > nul
echo [INFO] Cleaning up...
taskkill /IM mimikatz.exe /F > nul 2>&1
del %TEMP%\mimikatz.exe > nul
echo [SUCCESS] Test completed. Check the Dashboard for a CRITICAL alert.
