"""revoked_certs per audit e idempotenza post-reboot

Revision ID: 0011_revoked_certs
Revises: 0010_incidents
Create Date: 2026-09-12
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "0011_revoked_certs"
down_revision: Union[str, None] = "0010_incidents"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Idempotente: nei lab la tabella/indice erano stati creati manualmente
    # per l'audit; senza IF NOT EXISTS il riavvio crasha (fail-closed voluto).
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS revoked_certs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            agent_id VARCHAR(64) NOT NULL,
            serial VARCHAR(128),
            fingerprint VARCHAR(128),
            reason VARCHAR(255),
            revoked_by INTEGER REFERENCES users (id),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_revoked_certs_agent_id ON revoked_certs (agent_id)")

def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_revoked_certs_agent_id")
    op.execute("DROP TABLE IF EXISTS revoked_certs")
